spring:
  data:
    redis:
      host: coffee-shout-test-f6yew9.serverless.apn2.cache.amazonaws.com
      port: 6379
      ssl:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

redisson:
  enabled: true

room:
  qr:
    prefix: "https://dev.coffee-shout.com/join/"

websocket:
  inbound:
    virtual-threads: true
  docs:
    server-url: "https://api.dev.coffee-shout.com/ws"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
